BG={
    currenttab:"",
    selectedWebsites:[],
    contextMenueParentId:0,
    init:function(){
        BG.loadData(Data);
        BG.changeSelectedTab();
        BG.createContextMenu();
    },
    createContextMenu:function(){
        createProperties={
            "title":"share"
        };
        BG.contextMenueParentId=chrome.contextMenus.create(createProperties);
    },
    share:function(sharedSite,tab){
        window.open(sharedSite.url+tab,"mywindow","width=500,height=400");
    },
    setup:function(){
        chrome.tabs.getSelected(null, function(tab) {
            BG.currenttab=tab;
        });
    },
    changeSelectedTab:function(){
        BG.setup();
        chrome.tabs.onSelectionChanged.addListener(function(){
            chrome.tabs.getSelected(null, function(tab) {
                BG.currenttab=tab;
            });
        })
    },
    createNewContextMenue:function(site,parentId){
        createProperties={
            "title":site.name,
            "contexts":["all"],
            "onclick":function(OnClickData,tab){
                BG.share(site,tab.url);
            },
            "parentId":parentId
        };
        chrome.contextMenus.create(createProperties);
    },
    loadData:function(Data){
        localStorage.Data=JSON.stringify(Data)
    }
    
}
