var Data={
    websites:[
    {
        'name':'Facebook',
        'url':'http://www.facebook.com/sharer.php?u=',
        'selected':false
    },{
        'name':'Twitter',
        'url':'http://twitter.com/share?url=',
        'selected':false
    },{
        'name':'Gmail',
        'url':'http://www.facebook.com/sharer.php?u=',
        'selected':false
    },{
        'name':'Hotmail',
        'url':'http://www.facebook.com/sharer.php?u=',
        'selected':false
    },{
        'name':'GoogleBookmarks',
        'url':'http://www.facebook.com/sharer.php?u=',
        'selected':false
    },{
        'name':'Linkedin',
        'url':'http://www.facebook.com/sharer.php?u=',
        'selected':false
    },{
        'name':'YahooMail',
        'url':'http://www.facebook.com/sharer.php?u=',
        'selected':false
    }
    ]    
}
